add music-wheel of color
knewter/colluder pull request #3
Opened 2016-10-10 16:12 UTC by ManuScriptHub

Hi Josh

Here is our little contribution to the colluder. if you like it, we can build it out some day and maybe show a ring per octave or use it to compose more easily or the like. 

I'm Baaaaack!!! Elm has me again.

Ttys, Cheerio
Manuel

2016-10-10 21:02 UTC, knewter requested changes
This is awesome!  Just checked it out.  Just looks like elm-package was run from the root and an artifact made it into the commit.  Pumped to merge it if you can remove that file.

2016-10-10 21:02 UTC, knewter commented on elm-package.json
> +{
Can you remove this file from the root?

2016-10-11 07:09 UTC, ManuScriptHub commented on elm-package.json
> +{
i think, i just did, by pushing my changes?

2016-10-11 07:09 UTC, ManuScriptHub commented on elm-package.json
> +{
or did I?

2016-10-11 13:58 UTC, knewter approved these changes

2016-10-11 13:58 UTC, merged

2016-10-11 13:58 UTC, knewter commented
woot!  thanks, looks awesome